### ISSUE TITLE
Only 30 items are shown in map.apps Manager

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-github-manager#1]
The request returns only 30 results. In total 44 items are available.

**Comment by ghost** [comment]
There is a problem with the github search API. We run into an internal timeout, so only incomplete results are returned. See also [here](https://developer.github.com/v3/search/#timeouts-and-incomplete-results).

The motivation why we use the _/search/repositories_  endpoint was that we could filter for map.apps tags. Using the _/users/:user/repos_ endpoint will not return any information which we could use to identify map.apps bundles.

**ToDo**: Use another API endpoint  or try to find a workaround

**Comment by meyero** [comment]
This limitation is due to the fact that the default page size is 30 items (see https://developer.github.com/v3/#pagination). A quick workaround ist to add "&per_page=100" to the request. Since we currently provide less than 100 bundles this will work for the moment.

The best way is to change the store implementation: Currently the store is based on a memory store. The GitHub endpoint is queried only once when the store instance is being created. All items are kept im memory. Ideally, the store implements a query function that calls the endpoint everytime the function is called. In this case we won't have any limitations.

**Comment by ghost** [comment]
Thanks for the contribution! I also noticed that github sends the next and last page in the header of the request, maybe we also could make use of that when refactoring the store.

**Comment by matthiasstein** [comment]
https://github.com/conterra/mapapps-github-manager/releases/tag/1.0.1 returns 100 results.
